defaultPortal: test
portals:
  - name: test
    portalId: 145430867
    env: prod
    personalAccessKey: ${HUBSPOT_PAT}
    sandboxAccountType: DEVELOPER_ACCOUNT
    accountType: STANDARD
    appId: 9520370
project:
  name: external-url-viewer
  srcDir: src/app
  deployRoot: dist